title: Dexcom
description: "Holiday"
owner_name: Vibha, Maryam, Aditi, Collin, Anyi, Shriya
github_username: nighthawkcoders
github_repo: "dexcom_frontend" 
baseurl: "/dexcom_frontend"
future: true
remote_theme: jekyll/minima
minima:
  skin: dark
# remote_theme: pages-themes/midnight@v0.2.0
# remote_theme: pages-themes/dinky@v0.2.0
# remote_theme: pages-themes/minimal@v0.2.0
# remote_theme: pages-themes/cayman@v0.2.0
# remote_theme: pages-themes/time-machine@v0.2.0
plugins:
  - jekyll-remote-theme
header_pages:
  - navigation/titanic.md
  - navigation/pintheneedle.md
  - navigation/foodchoice.md

 
